import Head from 'next/head';
import { Heading } from '@/components/heading/Heading';

function HomeView() {
  return (
    <>
      <Head>
        <title>Won Games</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Heading>Welcome to Won Games</Heading>
      </main>
    </>
  );
}

export default HomeView;
