import Head from 'next/head';

function HomeView() {
  return (
    <>
      <Head>
        <title>Won Games</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Welcome to Won Games</h1>
      </main>
    </>
  );
}

export default HomeView;
